version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ee
    container_name: gitlab
    restart: always
    hostname: 'gitlab.fbi.com'
    privileged: true
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.fbi.com'

    ports:
      - '3012:80'
      - '3013:22'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    shm_size: '256m'
volumes:
  gitlab_config:
  gitlab_data:
