name: agolademo

services:
  gitea:
    build: images/gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - _VERSION=1001
    configs:
      - source: gitea
        target: /data/gitea/conf/app.ini
    hostname: gitea.fbi.com
    networks:
      net1:
        ipv4_address: 172.30.0.3
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3015:3000"
      - "3016:4000"
      - "2222:22"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  gitea_runner:
    image: gitea/act_runner:latest
    deploy:
      mode: replicated
      replicas: 2

    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      net1:

    environment:
      GITEA_INSTANCE_URL: http://172.30.0.3:3000
      GITEA_RUNNER_REGISTRATION_TOKEN: RA3mWOsKlHNWI6jVy7Wy9CWpg7QTnvyoG32s3KqT
      GITEA_RUNNER_NAME: main
      CONFIG_FILE: /config.yaml
      _VERSION: 1005

    configs:
      - source: gitea_runner
        target: /config.yaml

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    container_name: nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    container_name: nsqd
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    container_name: nsqadmin
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"

networks:
  net1:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

volumes:
  gitea-data:

configs:
  gitea:
    file: ./gitea/app.ini
  gitea_runner:
    file: ./gitea/runner.yaml
